#!/bin/sh
# Authenticated, atomic config upload. Never accepts or stores a subscription URL.
echo "Content-Type: application/json; charset=utf-8"
echo "Cache-Control: no-store"
echo ""
DIR=/data/other_vol/proxy
TOKENF=/data/other_vol/console/token
EXPECT=$(cat "$TOKENF" 2>/dev/null)
LEN=${CONTENT_LENGTH:-0}

fail() { rm -f "$DIR/config.request" "$DIR/config.upload"; echo "{\"ok\":false,\"error\":\"$1\"}"; exit 0; }
[ "$REQUEST_METHOD" = "POST" ] || fail "仅允许 POST"
[ -n "$EXPECT" ] || fail "路由器未设置控制令牌"
case "$LEN" in ''|*[!0-9]*) fail "Content-Length 无效";; esac
[ "$LEN" -gt 0 ] && [ "$LEN" -le 2097152 ] || fail "配置大小不合法"
dd bs=1 count="$LEN" of="$DIR/config.request" 2>/dev/null || fail "读取配置失败"
TOKEN=$(head -n 1 "$DIR/config.request" | tr -d '\r\n')
[ "$TOKEN" = "$EXPECT" ] || fail "控制令牌错误"
tail -n +2 "$DIR/config.request" > "$DIR/config.upload"
rm -f "$DIR/config.request"
chmod 600 "$DIR/config.upload"
grep -q '^# Generated by CampusNetManager' "$DIR/config.upload" || fail "配置来源标记缺失"
"$DIR/mihomo" -t -d "$DIR" -f "$DIR/config.upload" >/dev/null 2>&1 || fail "mihomo 配置校验失败"

cp -f "$DIR/config.yaml" "$DIR/config.last-good.yaml" 2>/dev/null
mv -f "$DIR/config.upload" "$DIR/config.yaml" || fail "替换配置失败"
chmod 600 "$DIR/config.yaml"
rm -f "$DIR/transparent.enabled"
sh "$DIR/stop.sh" >/dev/null 2>&1
if ! sh "$DIR/start.sh" >/dev/null 2>&1; then
  cp -f "$DIR/config.last-good.yaml" "$DIR/config.yaml" 2>/dev/null
  sh "$DIR/start.sh" >/dev/null 2>&1
  fail "新配置启动失败，已恢复旧配置"
fi
CODE=$(curl -x http://127.0.0.1:7890 -L -sS -m 30 -o /dev/null \
    -w '%{http_code}' https://cp.cloudflare.com/generate_204)
if [ "$CODE" != "204" ]; then
  cp -f "$DIR/config.last-good.yaml" "$DIR/config.yaml" 2>/dev/null
  sh "$DIR/stop.sh" >/dev/null 2>&1
  sh "$DIR/start.sh" >/dev/null 2>&1
  fail "节点出口测试失败，已恢复旧配置"
fi
echo '{"ok":true,"mode":"explicit","port":7890}'
