charon {
  filelog {
    campusnet {
      path = /var/log/campusnet-ikev2.log
      default = 2
      flush_line = yes
      ike_name = yes
      log_level = yes
      time_format = %FT%T
    }
  }
}
